const desktop = document.createElement('div');
const wrapper = document.createElement('div');
const section1 = document.createElement('div');
const img = document.createElement('img');
const section2 = document.createElement('div');
const ptag = document.createElement('p');
const ptag2 = document.createElement('p');
const h1 = document.createElement('h1');
const price1 = document.createElement('h2');
const price2 = document.createElement('h4');
const rectenagle = document.createElement('div');
const imgTrash = document.createElement('img');
const addToCard = document.createElement('p');
document.body.append(desktop);
desktop.append(wrapper);
wrapper.append(section1);
wrapper.append(section2);
section1.append(img);
section2.append(ptag);
section2.append(h1);
section2.append(ptag2);
section2.append(price1);
section2.append(price2);
section2.append(rectenagle);
rectenagle.append(imgTrash);
rectenagle.append(addToCard);
console.log(ptag2);
desktop.style = `display: flex;
width: 1440px;
height: 800px;
justify-content: center;
align-items: center;
background: var(--cream-bg, #F2EAE2);`;

wrapper.style = ` width: 600px;
height: 450px;
flex-shrink: 0;
border-radius: 10px;
background: var(--pure-white, #fff);`;

section1.style = `width: 337.694px;height: 450px;`;
img.src = `https://s3-alpha-sig.figma.com/img/ae45/4123/eb2ee7736de7d5d296876bd9559b4050?Expires=1688342400&Signature=MeO2ABlrdngD7ciTGtzJNnD3L9d3h5jW1DhX7p1NgtPQxFTdu5ZVzttoPe0EZXPAyhT2Jo9SKLzBvoqxEWgRQgu9CwwYP~d9nR0Vxu1LOOJBhMpLqb0OgJ1vppCV5iDTi41bQYmRa6pKIEzJxfx-PnVVgC5VFPxgddfK83-JM3h0x9clEka75QrfP7xnBcOQJbOwF~XvT0~Z9H4PD~8wqRLApMGzu~lhds8CdbbEhIm6rXLbHF8HqqVWkq4Z6j2CWJ8RQCIxfihaCgDTdhT-EYGyCyOaS6VfoqJ3dPc6yUxtk0lxOBye~o2Slr41~js1JCxP0~5UW-UR8C63VtAk1g__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4`;
img.style = `width: 320.694px;
height: 450px;

border-top-left-radius: 10px;
border-bottom-left-radius: 10px;`;

section2.style = `display: flex;
flex-wrap: wrap;
height: 460px;
width: 300px;
margin:-450px 0px 0px 340px ;`;
ptag.innerHTML = `PERFUME`;
ptag.style = `width:92px;
height:15px;
  color: var(--aurometal-saurus, #6c7289);
  font-size: 12px;
  font-family: Montserrat;
  font-weight: 500;
  letter-spacing: 5px;
`;
h1.innerHTML = `Gabrielle Essence Eau De Parfum`;
h1.style = `display: flex;
width: 236px;
height: 96px;
flex-direction: column;
flex-shrink: 0;
color: var(--gunmetal, #1C232B);
font-size: 32px;
font-family: Fraunces;
font-weight: 700;
line-height: 32px;`;

ptag2.innerHTML = `A floral, solar and voluptuous interpretation composed by Olivier Polge, Perfumer-Creator for the House of CHANEL.`;
ptag2.style = ` width: 236px;
height: 97px;
display: flex;`

price1.innerHTML = `$149.99`;
price1.style = ` width: 127px;
height: 32px;
color: var(--deep-aquamarine, #3D8168);
font-size: 32px;
font-family: Fraunces;
font-weight: 700;
line-height: 32px;
`;
price2.innerHTML = `$169.99`;
price2.style = `display: flex;
justify-content: center;
text-decoration-line: strikethrough;
width: 48px;
height: 23px;
padding: 12px 10px 0px 0px;
color: var(--aurometal-saurus, #6C7289);
font-size: 13px;
font-family: Montserrat;
font-weight: 500;
line-height: 23px;
text-decoration: line-through;`;

rectenagle.style = `display: flex;
justify-content: center;
align-items: center;
width: 236px;
height: 48px;
margin-bottom:290px;
color: #ffffff;
border-radius: 8px;
cursor: pointer;
background: var(--deep-aquamarine, #3d8168);`;
imgTrash.src = 'Cart.png';

addToCard.innerHTML = `Add to Cart`;
addToCard.style = `color: var(--pure-white, #FFF);
font-size: 14px;
font-family: Montserrat;
font-weight: 700;
width: 85px;
height: 17px;
padding: 6px;
`;
console.log(section2);